### PR TITLE
PR to Make dropdown menu with color features like FOSSASIA.org and also enable expansion of menu

### PR DESCRIPTION
**Pull request by makoteq**
fixed for  https://github.com/OpnTec/opentechsummit.eu/issues/3
**Link to preview** : https://makoteq.github.io/opentechsummit.eu/

### CODE REVIEW

**Comment by makoteq** [comment]
@mariobehling

**Comment by mariobehling** [comment]
This does not solve the issue. The current CSS needs to be updated with the feature required.

**Review by mariobehling — CHANGES_REQUESTED** [review]
use the current theme css and update the feature.

**Comment by makoteq** [comment]
What about now? @mariobehling

**Comment by mariobehling** [comment]
I recommend you work together with your co-contributor on the issue. Indent and spacing was changed and it should not be changed. Only color overlay on scroll-over should be changed.

Please compare here: https://github.com/OpnTec/opentechsummit.eu/pull/5#issuecomment-568308431

Please help me here. I am making the same comments in different PRs. It is not a good use of time to repeat the same thing in different PRs. Please work together!

**Comment by makoteq** [comment]
@mariobehling I'll follow this other PR, sorry for problem

**Comment by makoteq** [comment]
@mariobehling I removed changes in spacing and I changed the hover  color

**Review by mariobehling — CHANGES_REQUESTED** [review]
Spacing in dropdown changed and menu items missing.

Screenshot from 2019-12-24 03-58-54

Expected: The spacing should not change and all menu items should be there.

**Comment by makoteq** [comment]
I removed max-height, and padding for menu so now it should be ok
New link to preview https://makoteq.github.io/opentechsummit.eu.custom/
@mariobehling

**Comment by makoteq** [comment]
@mariobehling what about now?

**Comment by mariobehling** [comment]
Still not as expected. Please compare exactly with fossasia.org

**Review by mariobehling — APPROVED** [review]
Very good!

**Pull request merged**
