### PR TITLE
Modified navbar dropdown

### PR DESCRIPTION
**Pull request by chamodperera**
preview link-https://chamodperera.github.io/opentechsummit.eu/
openevent

### CODE REVIEW

**Review by mariobehling — CHANGES_REQUESTED** [review]
The theme css and color were changed. This is not the goal. Keep the color and implement relevant changes in this 'orange css'.

**Comment by chamodperera** [comment]
changes have been done

**Review by mariobehling — CHANGES_REQUESTED** [review]
1. Please use the theme color -> orange.
2. Don't change the indent and spacing of the menu.

**Comment by chamodperera** [comment]
Changes have been done

opentec

**Comment by mariobehling** [comment]
Indent and spacing to edge of the dropdown was changed. Expected: It should not be changed. There should be the space to the "box edge" just as it is right now.

Screenshot from 2019-12-22 23-28-54
See screenshot: The space is not there anymore.

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please keep the spacing in the dropdown.

**Comment by makoteq** [comment]
@chamodperera can you update your preview link?

**Pull request closed without merging**
